const orderArray = [{
    id:1,
    orderDate: '2024-04-24',
    orderNumber: '#2221131',
    companyName: 'FMI Farms',
    deliveryDate: '2024-05-01',
    salesRep:'Jhone Doe',
    total:'$114.16',
    products:[{
        id:'2134966',
        title:'Baby Blue Euc. Green',
        preorder:'yes',
        source:'Miami',
        margin:'Fedex',
        unitCost:'$12.66',
       }, 
      {
        id: '2134967',
        title: 'Alstroemerias',
        preorder: 'no',
        source: 'Italy',
        margin: 'Fedex',
        unitCost: '$15.50',
      },
      {
        id: '2134968',
        title: 'Birch Snowed White',
        preorder: 'yes',
        source: 'Ecuador',
        margin: 'Fedex',
        unitCost: '$10.25',
      },
      {
        id: '2134969',
        title: 'Birch Red Glitter',
        preorder: 'yes',
        source: 'Colombia',
        margin: 'Fedex',
        unitCost: '$18.75',
      },
      {
        id: '2134970',
        title: 'Aster',
        preorder: 'no',
        source: 'Houston',
        margin: 'Fedex',
        unitCost: '$20.00',
      },
    ]
    },
    {
        orderDate: '2024-04-24',
        orderNumber: '#2221132',
        companyName: 'Floral Gardens',
        deliveryDate: '2024-05-01',
        salesRep: 'John Doe',
        total: '$114.16',
         products:[{
            id:'2134966',
            title:'Baby Blue Euc. Green',
            preorder:'yes',
            source:'Miami',
            margin:'Fedex',
            unitCost:'$12.66',
           }, 
          {
            id: '2134967',
            title: 'Alstroemerias',
            preorder: 'no',
            source: 'Italy',
            margin: 'Fedex',
            unitCost: '$15.50',
          },
          {
            id: '2134968',
            title: 'Birch Snowed White',
            preorder: 'yes',
            source: 'Ecuador',
            margin: 'Fedex',
            unitCost: '$10.25',
          }]
        },
      {
        orderDate: '2024-04-22',
        orderNumber: '#2221133',
        companyName: 'Blossom Blooms',
        deliveryDate: '2024-05-03',
        salesRep: 'Jane Smith',
        total: '$215.32',
        products:[{
            id:'2134966',
            title:'Baby Blue Euc. Green',
            preorder:'yes',
            source:'Miami',
            margin:'Fedex',
            unitCost:'$12.66',
           }, 
          {
            id: '2134967',
            title: 'Alstroemerias',
            preorder: 'no',
            source: 'Italy',
            margin: 'Fedex',
            unitCost: '$15.50',
          },
          {
            id: '2134968',
            title: 'Birch Snowed White',
            preorder: 'yes',
            source: 'Ecuador',
            margin: 'Fedex',
            unitCost: '$10.25',
          }]
      },
      {
        orderDate: '2024-04-25',
        orderNumber: '#2221134',
        companyName: 'Petals & Plants',
        deliveryDate: '2024-05-02',
        salesRep: 'Michael Johnson',
        total: '$312.50',
        products:[{
            id:'2134966',
            title:'Baby Blue Euc. Green',
            preorder:'yes',
            source:'Miami',
            margin:'Fedex',
            unitCost:'$12.66',
           }, 
          {
            id: '2134967',
            title: 'Alstroemerias',
            preorder: 'no',
            source: 'Italy',
            margin: 'Fedex',
            unitCost: '$15.50',
          },
          {
            id: '2134968',
            title: 'Birch Snowed White',
            preorder: 'yes',
            source: 'Ecuador',
            margin: 'Fedex',
            unitCost: '$10.25',
          }]
      },
      {
        orderDate: '2024-04-20',
        orderNumber: '#2221135',
        companyName: 'Garden Grove',
        deliveryDate: '2024-05-05',
        salesRep: 'Emily Brown',
        total: '$412.75',
        products:[{
            id:'2134966',
            title:'Baby Blue Euc. Green',
            preorder:'yes',
            source:'Miami',
            margin:'Fedex',
            unitCost:'$12.66',
           }, 
          {
            id: '2134967',
            title: 'Alstroemerias',
            preorder: 'no',
            source: 'Italy',
            margin: 'Fedex',
            unitCost: '$15.50',
          },
          {
            id: '2134968',
            title: 'Birch Snowed White',
            preorder: 'yes',
            source: 'Ecuador',
            margin: 'Fedex',
            unitCost: '$10.25',
          }]
      },
      {
        orderDate: '2024-04-28',
        orderNumber: '#2221136',
        companyName: 'Flower Fields',
        deliveryDate: '2024-05-04',
        salesRep: 'Robert Williams',
        total: '$517.89',
        products:[{
            id:'2134966',
            title:'Baby Blue Euc. Green',
            preorder:'yes',
            source:'Miami',
            margin:'Fedex',
            unitCost:'$12.66',
           }, 
          {
            id: '2134967',
            title: 'Alstroemerias',
            preorder: 'no',
            source: 'Italy',
            margin: 'Fedex',
            unitCost: '$15.50',
          },
          {
            id: '2134968',
            title: 'Birch Snowed White',
            preorder: 'yes',
            source: 'Ecuador',
            margin: 'Fedex',
            unitCost: '$10.25',
          }]
      },
    ];

    export default orderArray;