const CustomerDummyList = [
    {
      account_number: '1001',
      company_name: 'Tech Corp',
      full_name: 'John Doe',
      username: 'johndoe',
      phone: '(555) 123-4567',
      last_order_date: '2023-09-10',
      last_order_value: '$200.00',
      sales_rep: 'Jane Smith',
      order_entry: 'Online',
    },
    {
      account_number: '1002',
      company_name: 'Innovate Inc',
      full_name: 'Alice Johnson',
      username: 'alicej',
      phone: '(555) 234-5678',
      last_order_date: '2023-08-15',
      last_order_value: '$450.00',
      sales_rep: 'Bob White',
      order_entry: 'In Store',
    },
    {
      account_number: '1003',
      company_name: 'NextGen Solutions',
      full_name: 'Michael Brown',
      username: 'mikebrown',
      phone: '(555) 345-6789',
      last_order_date: '2023-09-01',
      last_order_value: '$780.00',
      sales_rep: 'Emily Davis',
      order_entry: 'Phone',
    },
    {
      account_number: '1004',
      company_name: 'BizSoft',
      full_name: 'Emma Green',
      username: 'emmagreen',
      phone: '(555) 456-7890',
      last_order_date: '2023-07-20',
      last_order_value: '$125.00',
      sales_rep: 'David Lee',
      order_entry: 'Online',
    },
    {
      account_number: '1005',
      company_name: 'Alpha Systems',
      full_name: 'William Carter',
      username: 'willcarter',
      phone: '(555) 567-8901',
      last_order_date: '2023-06-30',
      last_order_value: '$650.00',
      sales_rep: 'Olivia Martinez',
      order_entry: 'In Store',
    },
    {
      account_number: '1006',
      company_name: 'BetaTech',
      full_name: 'Sophia Clark',
      username: 'sophiac',
      phone: '(555) 678-9012',
      last_order_date: '2023-08-25',
      last_order_value: '$325.00',
      sales_rep: 'James Brown',
      order_entry: 'Online',
    },
    {
      account_number: '1007',
      company_name: 'Delta Corp',
      full_name: 'Liam Davis',
      username: 'liamdavis',
      phone: '(555) 789-0123',
      last_order_date: '2023-09-05',
      last_order_value: '$980.00',
      sales_rep: 'Sarah Taylor',
      order_entry: 'Phone',
    },
    {
      account_number: '1008',
      company_name: 'Giga Solutions',
      full_name: 'Mason Wilson',
      username: 'masonw',
      phone: '(555) 890-1234',
      last_order_date: '2023-08-10',
      last_order_value: '$410.00',
      sales_rep: 'Daniel Harris',
      order_entry: 'In Store',
    },
    {
      account_number: '1009',
      company_name: 'Omega Industries',
      full_name: 'Isabella Moore',
      username: 'isamoore',
      phone: '(555) 901-2345',
      last_order_date: '2023-07-25',
      last_order_value: '$270.00',
      sales_rep: 'Nancy Allen',
      order_entry: 'Online',
    },
    {
      account_number: '1010',
      company_name: 'PrimeTech',
      full_name: 'James Johnson',
      username: 'jimjohnson',
      phone: '(555) 123-4567',
      last_order_date: '2023-09-11',
      last_order_value: '$520.00',
      sales_rep: 'Peter Adams',
      order_entry: 'Phone',
    },
    {
      account_number: '1011',
      company_name: 'Xtra Solutions',
      full_name: 'Ava Lee',
      username: 'avalee',
      phone: '(555) 234-5678',
      last_order_date: '2023-07-13',
      last_order_value: '$860.00',
      sales_rep: 'Clara Stewart',
      order_entry: 'Online',
    },
    {
      account_number: '1012',
      company_name: 'Peak Innovations',
      full_name: 'Ethan Walker',
      username: 'ewalker',
      phone: '(555) 345-6789',
      last_order_date: '2023-08-01',
      last_order_value: '$340.00',
      sales_rep: 'John Evans',
      order_entry: 'In Store',
    },
    {
      account_number: '1013',
      company_name: 'TopTech Corp',
      full_name: 'Amelia Lewis',
      username: 'amlewis',
      phone: '(555) 456-7890',
      last_order_date: '2023-08-30',
      last_order_value: '$715.00',
      sales_rep: 'Olivia Scott',
      order_entry: 'Phone',
    },
    {
      account_number: '1014',
      company_name: 'Ultra Systems',
      full_name: 'Lucas Young',
      username: 'lucasyoung',
      phone: '(555) 567-8901',
      last_order_date: '2023-07-27',
      last_order_value: '$650.00',
      sales_rep: 'Henry Garcia',
      order_entry: 'Online',
    },
    {
      account_number: '1015',
      company_name: 'Fusion Tech',
      full_name: 'Mia White',
      username: 'miawhite',
      phone: '(555) 678-9012',
      last_order_date: '2023-06-20',
      last_order_value: '$370.00',
      sales_rep: 'Sophia Wilson',
      order_entry: 'Phone',
    },
    {
      account_number: '1016',
      company_name: 'Vanguard Solutions',
      full_name: 'Benjamin Hall',
      username: 'benhall',
      phone: '(555) 789-0123',
      last_order_date: '2023-09-09',
      last_order_value: '$530.00',
      sales_rep: 'Liam Harris',
      order_entry: 'In Store',
    },
    {
      account_number: '1017',
      company_name: 'Zenith Industries',
      full_name: 'Charlotte King',
      username: 'charlotteking',
      phone: '(555) 890-1234',
      last_order_date: '2023-08-20',
      last_order_value: '$200.00',
      sales_rep: 'Noah Allen',
      order_entry: 'Online',
    },
    {
      account_number: '1018',
      company_name: 'Pinnacle Corp',
      full_name: 'Jack Martinez',
      username: 'jackmartinez',
      phone: '(555) 901-2345',
      last_order_date: '2023-07-19',
      last_order_value: '$930.00',
      sales_rep: 'Lucas Moore',
      order_entry: 'Phone',
    },
    {
      account_number: '1019',
      company_name: 'NovaTech',
      full_name: 'Ella Thompson',
      username: 'ellathompson',
      phone: '(555) 012-3456',
      last_order_date: '2023-08-03',
      last_order_value: '$475.00',
      sales_rep: 'Emily Young',
      order_entry: 'In Store',
    },
    {
      account_number: '1020',
      company_name: 'Hyper Systems',
      full_name: 'Logan Hill',
      username: 'loganhill',
      phone: '(555) 123-4567',
      last_order_date: '2023-06-25',
      last_order_value: '$285.00',
      sales_rep: 'Jacob Harris',
      order_entry: 'Online',
    },
    {
      account_number: '1021',
      company_name: 'Infinity Solutions',
      full_name: 'Grace Nelson',
      username: 'gracenelson',
      phone: '(555) 234-5678',
      last_order_date: '2023-07-10',
      last_order_value: '$360.00',
      sales_rep: 'James Davis',
      order_entry: 'Phone',
    },
    {
      account_number: '1022',
      company_name: 'Apex Industries',
      full_name: 'Harper Rivera',
      username: 'harperrivera',
      phone: '(555) 345-6789',
      last_order_date: '2023-08-23',
      last_order_value: '$765.00',
      sales_rep: 'William Martinez',
      order_entry: 'In Store',
    },
    {
      account_number: '1023',
      company_name: 'Optimus Tech',
      full_name: 'Henry Lopez',
      username: 'henrylopez',
      phone: '(555) 456-7890',
      last_order_date: '2023-07-15',
      last_order_value: '$615.00',
      sales_rep: 'Elizabeth Scott',
      order_entry: 'Online',
    },
    {
      account_number: '1024',
      company_name: 'Vector Solutions',
      full_name: 'Zoe Perez',
      username: 'zoeperez',
      phone: '(555) 567-8901',
      last_order_date: '2023-09-06',
      last_order_value: '$990.00',
      sales_rep: 'Sophia Wilson',
      order_entry: 'Phone',
    },
    {
      account_number: '1025',
      company_name: 'Streamline Corp',
      full_name: 'Sebastian Carter',
      username: 'sebcarter',
      phone: '(555) 678-9012',
      last_order_date: '2023-09-12',
      last_order_value: '$850.00',
      sales_rep: 'Liam Brown',
      order_entry: 'In Store',
    },
  ];
  

  export default CustomerDummyList;